package christopher.nobles.casino;

public enum DeckType {
    STANDARD, SHUFFLED, HAND, BLACKJACK, GOFISH, UNO, WAR, DOUBLESTANDARD, TRIPPLESTANDARD, QUADRASTANDARD, DOUBLEBLACKJACK, TRIPPLEBLACKJACK
}
